name: CI

on:
  push:
    tags:
      - "*"


jobs:
  build:


    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set sha_short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Compile ps1 to exe
      run:  .\ps2exe.ps1 -iconFile CoolManage.ico -inputFile CoolManage.ps1 -version $env:VERSION -outputFile CoolManage.exe -title $env:title  -requireAdmin -copyright $env:copyright -noOutput -noError -noconsole -verbose 
      shell: powershell
      env:
        title: "Git commit ${{ steps.vars.outputs.sha_short }}"  
        copyright: "Andrew Kuripka" 
        VERSION: ${{ steps.get_version.outputs.VERSION }}     
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "CoolManage.exe"
        token: ${{ secrets.GITHUB_TOKEN }}

 
