name: CI

on: 
  push:
    branches: 
      - master 

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Display the path
      run:  .\ps2exe.ps1 -inputFile "CoolManage.ps1" -outputFile "Cool.exe" -noconsole
      shell: powershell      
 
