name: CI

on: 
  push:
    branches: 
      - master


jobs:
  build:


    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set sha_short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: powershell env 
      run:  echo $env:copyright
      shell: powershell
      env:
        title: "\"Git commit ${{ steps.vars.outputs.sha_short }}\""  
        copyright: "\"Andrew Kuripka\""
    - name: Compile ps1 to exe
      run:  .\ps2exe.ps1 -iconFile CoolManage.ico -inputFile CoolManage.ps1 -outputFile CoolManage.exe -title $env:title  -requireAdmin -copyright $env:copyright -noOutput -noError -noconsole -verbose 
      shell: powershell
      env:
        title: "\"Git commit ${{ steps.vars.outputs.sha_short }}\""  
        copyright: "\"Andrew Kuripka\""        
    - name: Upload
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build-${{ steps.vars.outputs.sha_short }}"
          files: "CoolManage.exe" 
 
