name: CI

on: 
  push:
    branches: 
      - master 

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    #- uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Display the path
      run:  powershell -Command "$host.version"
      shell: powershell
